Defining a function named renderEntry with a single parameter named e…
Aiden-Peace300/code-journal pull request #7
Opened 2023-08-02 00:37 UTC by Aiden-Peace300

…ntry. The function should return DOM tree for a single entry that matches the enntries created. Also creating a event listener on the document which listens for the DOMContentLoaded event that calls updataEntriesView() which will loop though the data.entries array and generate a DOM tree for each entry in the array and appending that DOM tree to  which selects the first ul element

2023-08-02 23:56 UTC, Aiden-Peace300 commented
![user can view their entry REVIEW](https://github.com/Aiden-Peace300/code-journal/assets/47370726/dcd494c3-de3f-4e6a-aa6a-9affc792f65b)

2023-08-03 15:51 UTC, shawnkost requested changes
Couple tweaks here Aiden!

2023-08-03 15:51 UTC, shawnkost commented on index.html
> +            <a id="navbar-entries-link" href="#entries"></a>
There should be some text inside this `a` element. It should say "Entries"

2023-08-03 15:51 UTC, shawnkost commented on index.html
> +          <li class="no-entries-message">No entries have been recorded yet.</li>
This shouldn't be inside the `ul`. This should just be a `p` element outside the `ul`

2023-08-03 16:08 UTC, shawnkost approved these changes
👍🏻

2023-08-03 16:09 UTC, merged